import express from "express";
import cors from "cors";
import cookieParser from "cookie-parser";
import userRouter from "./routers/user.router.js";
const app = express();
app.use(express.json());
app.use("/api/v1", userRouter);
app.use(cors());
app.use(cookieParser());
export default app;
